#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name kanivecs
git config --global user.email kanivecskristaps@gmail.com
#git commit -m "Git_upload_05"
git commit -m "Git_upload_$1"
git push origin main

