#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git conifg --global user.name kanivecs
git config --global user.email kanivecskristaps@gmail.com
git commit -m "Git_upload"
git push origin main

